### ISSUE TITLE
Toggle sidebar when clicking on browserAction icon

### ISSUE THREAD

**Issue by dannycolin** [mozillabrasil/sumo_live_helper#116]
**Step to reproduce**

1. Set "Always open questions in sidebar" in Preferences
1. Click on SUMO Live Helper browserAction icon to open the sidebar
1. Re-click to close the sidebar

**Actual Behavior**

If the sidebar is open and I click on the browserAction icon, it doesn't close the sidebar like it doesn't with the builtin sidebar icon.

**Expected Behavior**

The browserAction icon should toggle on and off the sidebar when we click on it.

**Comment by WesleyBranton** [comment]
This was originally how I intended it to work, but there are some limitations to the sidebarAction API that prevented it from working properly. Doing this would require a check to see if the sidebar is currently opening. There is [an API for that](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/isOpen), but it returns a promise. The problem is that using the `open()` or `close()` features will [not allow the code to wait for a promise](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).

It's quite easy to check if the sidebar is open, but it's not so easy when you can't use the promise from the built-in API. I played around a bit with having a `sidebarIsOpen` boolean variable and just periodically running a function that updated that value, but I couldn't find a reliable way to trigger that function so that the value in the variable will always be accurate.

Since I couldn't get that functionality working, I omitted it from the release. I can look at it some more and see if there is a good way to do it for a future release, but there's no guarantee that there _is_ a way to do it.

**Comment by dannycolin** [comment]
> Since I couldn't get that functionality working, I omitted it from the release. I can look at it some more and see if there is a good way to do it for a future release, but there's no guarantee that there is a way to do it.

No rush. We can put it in the "nice to have" list and focus on more urgent issues ;).
